# Porta TCP server
server.tcp.port = 50000

# Porta UDP server
server.udp.port = 50001

# Dimensione thredpool 
server.threadpool.size = 10

# Durata di una partita (in secondiì)
server.game.duration = 120

# File JSON con parole da indovinare
server.words.file = data/Connections_Data.json

# File dati
server.users.file = data/users.json

# File dati partite
server.game.state.file = data/game_state.json

# Persistenza dei dati
server.persistence.interval = 30